// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBZj2Agx1M5OYK1XFODOIfHk5OwhgZEpyw',
    appId: '1:392934908561:web:be230a932570bfb62dd530',
    messagingSenderId: '392934908561',
    projectId: 'flutter-login-app-752fd',
    authDomain: 'flutter-login-app-752fd.firebaseapp.com',
    storageBucket: 'flutter-login-app-752fd.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDlM_RlvKsnKFd4V5lb15ptFYkAVlMleN8',
    appId: '1:392934908561:android:b396fbf7621444aa2dd530',
    messagingSenderId: '392934908561',
    projectId: 'flutter-login-app-752fd',
    storageBucket: 'flutter-login-app-752fd.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDH1rEB3onTOY7hYtnFv6iAa-7MQE6O_DA',
    appId: '1:392934908561:ios:9ec776d6b29b4a7c2dd530',
    messagingSenderId: '392934908561',
    projectId: 'flutter-login-app-752fd',
    storageBucket: 'flutter-login-app-752fd.appspot.com',
    androidClientId: '392934908561-bprsg2nq60lqmmnggme2p720bbhll8me.apps.googleusercontent.com',
    iosClientId: '392934908561-e60p4nd0muha79p752hqfru9inc07om0.apps.googleusercontent.com',
    iosBundleId: 'com.example.firebaseApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDH1rEB3onTOY7hYtnFv6iAa-7MQE6O_DA',
    appId: '1:392934908561:ios:9ec776d6b29b4a7c2dd530',
    messagingSenderId: '392934908561',
    projectId: 'flutter-login-app-752fd',
    storageBucket: 'flutter-login-app-752fd.appspot.com',
    androidClientId: '392934908561-bprsg2nq60lqmmnggme2p720bbhll8me.apps.googleusercontent.com',
    iosClientId: '392934908561-e60p4nd0muha79p752hqfru9inc07om0.apps.googleusercontent.com',
    iosBundleId: 'com.example.firebaseApp',
  );
}
